### ISSUE TITLE
[Bug]: Incorrect estimated geometric accuracy values assigned to settings.yaml

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pcm#621]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

The current values assigned for the estimated geometric accuracy values in settings.yaml is as follows:

```
 ESTIMATED_GEOMETRIC_ACCURACY:
    BIAS_X: -72.0
    BIAS_Y: -67.0
    STDDEV_X: 70.0
    STDDEV_Y: 62.0
```

These values are incorrect, and should be decimals.

### What did you expect?

These values were entered incorrectly ( 🙇 ), and should be set to the following:

```
 ESTIMATED_GEOMETRIC_ACCURACY:
    BIAS_X: -0.72
    BIAS_Y: -0.67
    STDDEV_X: 0.70
    STDDEV_Y: 0.62
```

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```
